version: "alpha"
schema: "core"
os:
    name: "macos"
    shell: "bash"
    packages:
        # Utilities
        - "bash"
        - "git"
        - "openssl"
        - "wget"
        - "curl"
        - "jq"
        - "tmux"
        - "tree"
        - "mmv"
        - "unrar"
        - "nmap"
        - "webp"

        # Editors
        - "vim"
        - "nano"

        # Plugins
        - "diff-so-fancy"

        # GNU Utilities
        - "coreutils"
        - "findutils"
        - "grep"
        - "gnu-tar"
        - "gnu-sed"
        - "gawk"
        - "gzip"
        - "gpg2"

        # Linters
        - "shellcheck"

        # Build Systems
        - "automake"
        - "make"
        - "cmake"

        # Language Runtimes (might be able to be moved into pydotfiles)
        # - "node"  # Not something I normally need

        # - name: "gradle"
        #  dependency: "java"

        # For Jekyll blog
        - "imagemagick@6"
    applications:
        # Common apps
        - "protonvpn"
        - "flux"
        - "atom"
        - "jetbrains-toolbox"
        - "google-chrome"
        - "firefox"
        - "vlc"
        - "qbittorrent"

        - "mactex" # Note: installation takes a looong time
        - "texmaker"
        - "discord"
        - "java"

        - "iterm2"
		- "signal"
        # Uncommon apps (may be still useful)
        - "filezilla"

    default_dock:
    - "Launchpad"
    - "Notes"
    - "iTunes"
    - "App Store"
    - "System Preferences"
    - "Firefox"
    default_settings_file: "default-settings.json"

actions:
- action: copy
  files:
    "fonts/FreeMono.ttf": "~/Library/Fonts/FreeMono.ttf"
- action: symlink
  files:
    "com.googlecode.iterm2.plist": "~/Library/Preferences/com.googlecode.iterm2.plist"
- action: symlink
  files:
    "bash_profile": "~/.bash_profile"
  hidden: true
- action: symlink
  files:
    "~/.motd": "/etc/motd"
  sudo: true
  absolute: true
