version: "alpha"
schema: "core"
os:
    name: "linux"
    shell: "bash"
    package_manager: "apt"
    packages:
        # Common dependencies
        - wget                  # Used in general downloading
        - git                   # Used in general project upkeep
        - unzip                 # Used with dealing with cached dotfile files
        - build-essential       # Used in pre-compiling rbenv

actions:
    - action: symlink
      files:
          "profile.symlink": "~/.profile"
      hidden: true
    - action: script
      files:
          "setup_diff_so_fancy": "_"
profile: "core"
