name: Build dotfile build packages

on:
  push:
    branches:
      - source
  schedule:
    # Runs on the 1st of every month at 4PM
    - cron: "0 16 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: "Jason Yao"
  GIT_AUTHOR_EMAIL: "Hello@JasonYao.com"
  BRANCH_REF_NAME: ${{ github.head_ref }}
  SHA_COMMIT_HASH: ${{ github.sha }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Deploy pipeline metadata
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Extracts the current branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: echo "🔎 The name of your branch is ${{ steps.extract_branch.outputs.branch }} and your repository is ${{ github.repository }}."

      # Sets up environment
      - name: Checkout repo code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Python 3 setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Install pydotfiles
        run: pip install pydotfiles

      - name: Generate release packages
        run: pydotfiles build
