#!/usr/bin/env bash

##
# Sets up desktop background pictures and spaces
##

function info () {
    printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

function user () {
    printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
}

function success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

function warn () {
    printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
}

function fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
    echo ''
    exit 1
}

info "Background Image: Checking background image status"

# Note the enclosing single quotes around bash variables when trying to use them in applescripts
if osascript -e 'tell application "System Events" to set picture of every desktop to ("img/background1.png" as POSIX file as alias)' ; then
    success "Background: Desktop image is now correctly set"
else
    fail "Background: Desktop image failed to be set"
fi
